// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBif9V1AoL38_qhnYiMjuNGI0P5qWG92kE',
    appId: '1:927836151477:web:b84b2c0686a4cd5c02a8fc',
    messagingSenderId: '927836151477',
    projectId: 'mealdb-7dd7a',
    authDomain: 'mealdb-7dd7a.firebaseapp.com',
    storageBucket: 'mealdb-7dd7a.appspot.com',
    measurementId: 'G-BVWYVKP74R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYmn2h42qnUztd_7cJ6zT7uOIgmtk3NeQ',
    appId: '1:927836151477:android:8a6c304604e3b0f302a8fc',
    messagingSenderId: '927836151477',
    projectId: 'mealdb-7dd7a',
    storageBucket: 'mealdb-7dd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_fyhb5yOJWzfEhQc-GVnB1ZCGMNk_qo',
    appId: '1:927836151477:ios:0637f842abc7223602a8fc',
    messagingSenderId: '927836151477',
    projectId: 'mealdb-7dd7a',
    storageBucket: 'mealdb-7dd7a.appspot.com',
    iosBundleId: 'com.example.mealDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU_fyhb5yOJWzfEhQc-GVnB1ZCGMNk_qo',
    appId: '1:927836151477:ios:6aa7dc68b9e3a41a02a8fc',
    messagingSenderId: '927836151477',
    projectId: 'mealdb-7dd7a',
    storageBucket: 'mealdb-7dd7a.appspot.com',
    iosBundleId: 'com.example.mealDb.RunnerTests',
  );
}
