// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jUyBJFepoe0cts3mlnxPW1n9j0AGXp4',
    appId: '1:828211559120:web:bc984a85cd5fc3ba68fcd5',
    messagingSenderId: '828211559120',
    projectId: 'flavourverse-3ed34',
    authDomain: 'flavourverse-3ed34.firebaseapp.com',
    storageBucket: 'flavourverse-3ed34.appspot.com',
    measurementId: 'G-P904G9VCKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb5Z9SHUCiB8_ASc-QW2uqHu9Uvtqw-Qc',
    appId: '1:828211559120:android:d16712c799615e1168fcd5',
    messagingSenderId: '828211559120',
    projectId: 'flavourverse-3ed34',
    storageBucket: 'flavourverse-3ed34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5PCHuw3oBFHej0XuhwgbzkkccC1q-HE',
    appId: '1:828211559120:ios:9f04973df28f08a368fcd5',
    messagingSenderId: '828211559120',
    projectId: 'flavourverse-3ed34',
    storageBucket: 'flavourverse-3ed34.appspot.com',
    iosBundleId: 'com.example.flavourVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5PCHuw3oBFHej0XuhwgbzkkccC1q-HE',
    appId: '1:828211559120:ios:9f04973df28f08a368fcd5',
    messagingSenderId: '828211559120',
    projectId: 'flavourverse-3ed34',
    storageBucket: 'flavourverse-3ed34.appspot.com',
    iosBundleId: 'com.example.flavourVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_jUyBJFepoe0cts3mlnxPW1n9j0AGXp4',
    appId: '1:828211559120:web:617e0d24f8f316b568fcd5',
    messagingSenderId: '828211559120',
    projectId: 'flavourverse-3ed34',
    authDomain: 'flavourverse-3ed34.firebaseapp.com',
    storageBucket: 'flavourverse-3ed34.appspot.com',
    measurementId: 'G-R9WK5NFS8L',
  );

}